
on: 
  push:
    paths: ['**.R', 'tests/**', '**.Rd', '**.c', '**.cpp', '**.h', '**.hpp', 'DESCRIPTION', 'NAMESPACE', 'MAKEVARS', 'MAKEVARS.win', '**.yml']
  pull_request:
    paths: ['**.R', 'tests/**', '**.Rd', '**.c', '**.cpp', '**.h', '**.hpp', 'DESCRIPTION', 'NAMESPACE', 'MAKEVARS', 'MAKEVARS.win']
  schedule:
    - cron:  '13 12 * * 1-5'

name: unit-tests

jobs:
  debugging:
    runs-on: ubuntu-latest

    steps:
      - name: print variables
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$GITHUB_EVENT_NAME"
        shell: bash

  call-jasp-unit-tests-workflow:

    if: GITHUB_EVENT_NAME != 'schedule'
    # if: GITHUB_EVENT_NAME != 'schedule' || GITHUB_REPOSITORY_OWNER == 'jasp-stats'

    uses: vandenman/jasp-actions/.github/workflows/unittest.yml@reuseable_workflow_unittests
    with:
      needs_JAGS:   false
      needs_igraph: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
