
on: 
  push:
    paths: ['**.R', 'tests/**', '**.Rd', '**.c', '**.cpp', '**.h', '**.hpp', 'DESCRIPTION', 'NAMESPACE', 'MAKEVARS', 'MAKEVARS.win', '**.yml']
  pull_request:
    paths: ['**.R', 'tests/**', '**.Rd', '**.c', '**.cpp', '**.h', '**.hpp', 'DESCRIPTION', 'NAMESPACE', 'MAKEVARS', 'MAKEVARS.win']
  schedule:
    - cron:  '13 12 * * 1-5'

name: unit-tests

jobs:

  unit-tests:

    if: github.event.name != 'schedule'
    # if: github.event.name != 'schedule' || github.repository.owner == 'jasp-stats'

    uses: vandenman/jasp-actions/.github/workflows/unittests.yml@reuseable_workflow_unittests
    with:
      needs_JAGS:   false
      needs_igraph: true
